[dependencies]
unicode-segmentation = "1.3.0"
criterion = "0.3"

[features]
grapheme = []

[package]
edition = "2018"
name = "reverse_string"
version = "1.2.0"

[[bench]]
name = "my_benchmark"
harness = false
